package:
  name: jinwu
  version: "0.0.3"

source:
  url: https://pypi.io/packages/source/j/jinwu/jinwu-0.0.3.tar.gz
  sha256: "0b2885dfd44fbaaa3ff5ba42fd3991e5e5e8d1f6927c4592e248f6bdf34534e9 "

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

dependencies:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - numpy
    - scipy
    - astropy
    - emcee

about:
  home: https://github.com/xinxiangsun/jinwu
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Joint inference and physical modeling toolkit for high-energy transient light-curve and spectral analysis."
  description: |
    JinWu is a toolkit for joint inference and physical modeling of high-energy transient light-curves and spectra, supporting unified analysis and flexible extension.
  doc_url: https://github.com/xinxiangsun/jinwu/blob/master/README.md
  dev_url: https://github.com/xinxiangsun/jinwu

extra:
  recipe-maintainers:
    - xinxiangsun
